// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prjMvcCore第四組.Models;

#nullable disable

namespace prjMvcCoreMSIC173.Migrations
{
    [DbContext(typeof(MidprjDb2Context))]
    partial class MidprjDb2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TRecipeTag", b =>
                {
                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<int>("FTagId")
                        .HasColumnType("int")
                        .HasColumnName("fTagId");

                    b.HasKey("FRecipeId", "FTagId")
                        .HasName("PK_RecipeTags");

                    b.HasIndex("FTagId");

                    b.ToTable("tRecipeTag", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TApply", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<DateTime>("FApplyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fApplyDate");

                    b.Property<string>("FIdCard")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("fIdCard");

                    b.Property<string>("FIdNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fIdNum");

                    b.Property<int>("FStatus")
                        .HasColumnType("int")
                        .HasColumnName("fStatus");

                    b.Property<string>("FStoreDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("fStoreDescription");

                    b.Property<string>("FStoreName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fStoreName");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.HasKey("FId")
                        .HasName("PK__tApply__D9F8227C94FB5E86");

                    b.HasIndex("FUserId");

                    b.ToTable("tApply", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TAuditLog", b =>
                {
                    b.Property<int>("FLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fLogId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FLogId"));

                    b.Property<string>("FAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fAction");

                    b.Property<int>("FAdminUserId")
                        .HasColumnType("int")
                        .HasColumnName("fAdminUserId");

                    b.Property<DateTime>("FExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fExecutedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fReason");

                    b.Property<int>("FTargetRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fTargetRecipeId");

                    b.HasKey("FLogId")
                        .HasName("PK__tAuditLo__3CD1938B75982076");

                    b.ToTable("tAuditLog", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TBrand", b =>
                {
                    b.Property<int>("FBrandId")
                        .HasColumnType("int")
                        .HasColumnName("fBrandId");

                    b.Property<string>("FBrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fBrandName");

                    b.HasKey("FBrandId")
                        .HasName("PK_Brand");

                    b.ToTable("tBrand", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TCoupon", b =>
                {
                    b.Property<int>("FCouponId")
                        .HasColumnType("int")
                        .HasColumnName("fCouponId");

                    b.Property<string>("FCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fCode");

                    b.Property<string>("FDiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fDiscountType");

                    b.Property<decimal>("FDiscountValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fDiscountValue");

                    b.Property<DateTime?>("FEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fEndDate");

                    b.Property<bool?>("FIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fIsActive");

                    b.Property<decimal?>("FMaxDiscountAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fMaxDiscountAmount");

                    b.Property<decimal?>("FMinPurchaseAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fMinPurchaseAmount");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fName");

                    b.Property<string>("FScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fScopeType");

                    b.Property<int?>("FSellerId")
                        .HasColumnType("int")
                        .HasColumnName("fSeller_Id");

                    b.Property<DateTime>("FStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fStartDate");

                    b.HasKey("FCouponId")
                        .HasName("PK_Coupon");

                    b.HasIndex(new[] { "FCode" }, "UQ_Coupon_Code")
                        .IsUnique()
                        .HasFilter("[fCode] IS NOT NULL");

                    b.ToTable("tCoupon", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TIngredient", b =>
                {
                    b.Property<int>("FIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fIngredientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FIngredientId"));

                    b.Property<decimal>("FCaloriesPerUnit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fCaloriesPerUnit");

                    b.Property<string>("FCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fCategory");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fName");

                    b.Property<string>("FStandardUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fStandardUnit");

                    b.HasKey("FIngredientId")
                        .HasName("PK__tIngredi__3A47A04554E34ADB");

                    b.ToTable("tIngredient", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TMapFavorite", b =>
                {
                    b.Property<long>("FFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fFavoriteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FFavoriteId"));

                    b.Property<DateTime>("FCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fCreatedTime")
                        .HasDefaultValueSql("(getdate())", "DF_Favorite_CreatedTime");

                    b.Property<long>("FRestaurantId")
                        .HasColumnType("bigint")
                        .HasColumnName("fRestaurantID");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_ID");

                    b.HasKey("FFavoriteId")
                        .HasName("PK__tMapFavo__BAA205373544AC73");

                    b.HasIndex("FRestaurantId");

                    b.HasIndex("FUsersId");

                    b.ToTable("tMapFavorite", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TMessageTable", b =>
                {
                    b.Property<int>("FMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fMessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FMessageId"));

                    b.Property<int>("FLikes")
                        .HasColumnType("int")
                        .HasColumnName("fLikes");

                    b.Property<string>("FMessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fMessageContent");

                    b.Property<DateTime>("FMessageDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fMessageDate");

                    b.Property<byte>("FMessageState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("fMessageState")
                        .HasDefaultValue((byte)1, "DF_MessageTable_fMessageState");

                    b.Property<int>("FPostId")
                        .HasColumnType("int")
                        .HasColumnName("fPostID");

                    b.Property<int>("FReplyMessageId")
                        .HasColumnType("int")
                        .HasColumnName("fReplyMessageID");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUser_Id");

                    b.Property<int>("FViews")
                        .HasColumnType("int")
                        .HasColumnName("fViews");

                    b.HasKey("FMessageId")
                        .HasName("PK_MessageTable");

                    b.HasIndex("FPostId");

                    b.HasIndex("FUserId");

                    b.ToTable("tMessageTable", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrder", b =>
                {
                    b.Property<long>("FOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FOrderId"));

                    b.Property<int>("FCancellationStatus")
                        .HasColumnType("int")
                        .HasColumnName("fCancellationStatus")
                        .HasComment("取消狀態：0 無取消申請 / 1 待回覆 / 2 已取消 / 3 拒絕取消");

                    b.Property<bool>("FIsShippingConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("fIsShippingConfirmed")
                        .HasComment("賣家是否已確認/列印出貨單（0 未確認 1 已確認/已列印）");

                    b.Property<DateTime>("FOrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fOrderDate");

                    b.Property<string>("FOrderNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fOrderNo");

                    b.Property<int>("FOrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("fOrderStatus")
                        .HasComment("訂單狀態：0 待處理 / 1 已成立 / 2 已完成 / 3 已取消");

                    b.Property<int>("FPaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("fPaymentStatus")
                        .HasComment("付款狀態：0 待付款 / 1 已付款 / 2 待退款 / 3 已退款");

                    b.Property<decimal>("FProductDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fProductDiscount");

                    b.Property<string>("FRecipientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fRecipientName");

                    b.Property<string>("FRecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fRecipientPhone");

                    b.Property<int>("FReturnStatus")
                        .HasColumnType("int")
                        .HasColumnName("fReturnStatus")
                        .HasComment("退貨狀態：0 無退貨 / 1 待處理 / 2 已處理");

                    b.Property<int>("FSellerId")
                        .HasColumnType("int")
                        .HasColumnName("fSeller_Id");

                    b.Property<string>("FShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fShippingAddress");

                    b.Property<decimal>("FShippingDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fShippingDiscount");

                    b.Property<decimal>("FShippingFee")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fShippingFee");

                    b.Property<string>("FShippingMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fShippingMethod");

                    b.Property<int>("FShippingStatus")
                        .HasColumnType("int")
                        .HasColumnName("fShippingStatus")
                        .HasComment("運送狀態：0 待出貨 / 1 運送中 / 2 已送達 / 3 運送失敗 / 4 退回包裹運送中 / 5 賣家已取回退件");

                    b.Property<decimal>("FTotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fTotalAmount");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_Id");

                    b.HasKey("FOrderId")
                        .HasName("PK_Orders");

                    b.HasIndex(new[] { "FOrderNo" }, "UQ_Orders_OrderNo")
                        .IsUnique();

                    b.ToTable("tOrder", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrderDetail", b =>
                {
                    b.Property<int>("FOrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fOrderDetailsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FOrderDetailsId"));

                    b.Property<long>("FOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("fOrderID");

                    b.Property<int>("FProductId")
                        .HasColumnType("int")
                        .HasColumnName("fProductID");

                    b.Property<int>("FQuantity")
                        .HasColumnType("int")
                        .HasColumnName("fQuantity");

                    b.Property<decimal>("FUnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fUnitPrice");

                    b.HasKey("FOrderDetailsId")
                        .HasName("PK_OrderDetails");

                    b.HasIndex("FOrderId");

                    b.HasIndex("FProductId");

                    b.ToTable("tOrderDetail", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrderDiscount", b =>
                {
                    b.Property<int>("FOrderDiscountId")
                        .HasColumnType("int")
                        .HasColumnName("fOrderDiscountId");

                    b.Property<decimal>("FAppliedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fAppliedAmount");

                    b.Property<int>("FCouponId")
                        .HasColumnType("int")
                        .HasColumnName("fCouponId");

                    b.Property<string>("FDiscountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fDiscountName");

                    b.Property<string>("FDiscountScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fDiscountScope");

                    b.Property<string>("FDiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fDiscountType");

                    b.Property<long>("FOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("fOrderID");

                    b.HasKey("FOrderDiscountId")
                        .HasName("PK_OrderDiscounts");

                    b.HasIndex("FCouponId");

                    b.HasIndex("FOrderId");

                    b.ToTable("tOrderDiscount", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TPostTable", b =>
                {
                    b.Property<int>("FPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fPostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FPostId"));

                    b.Property<int>("FLikes")
                        .HasColumnType("int")
                        .HasColumnName("fLikes");

                    b.Property<string>("FPostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fPostContent");

                    b.Property<DateTime>("FPostDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fPostDate");

                    b.Property<byte>("FPostState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("fPostState")
                        .HasDefaultValue((byte)1, "DF_PostTable_fPostState");

                    b.Property<string>("FTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fTitle");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUser_Id");

                    b.Property<int>("FViews")
                        .HasColumnType("int")
                        .HasColumnName("fViews");

                    b.HasKey("FPostId")
                        .HasName("PK_PostTable");

                    b.HasIndex("FUserId");

                    b.ToTable("tPostTable", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProduct", b =>
                {
                    b.Property<int>("FProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FProductId"));

                    b.Property<string>("FAttributesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fAttributesJson");

                    b.Property<int?>("FBrandId")
                        .HasColumnType("int")
                        .HasColumnName("fBrandId");

                    b.Property<string>("FDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fDescription");

                    b.Property<DateOnly?>("FExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("fExpirationDate");

                    b.Property<DateOnly>("FManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("fManufacturingDate");

                    b.Property<decimal>("FPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fPrice");

                    b.Property<DateTime>("FProductDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fProductDate");

                    b.Property<string>("FProductNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fProductNo");

                    b.Property<byte?>("FProductStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("fProductStatus")
                        .HasComment("商品狀態：0 審核中 / 1 架上商品 / 2 已售完 / 3 未上架 / 4 已違規");

                    b.Property<string>("FProductname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fProductname");

                    b.Property<int>("FProductsCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("fProductsCategoryID");

                    b.Property<int>("FReportCount")
                        .HasColumnType("int")
                        .HasColumnName("fReportCount");

                    b.Property<int>("FSellerId")
                        .HasColumnType("int")
                        .HasColumnName("fSeller_Id");

                    b.Property<int>("FStock")
                        .HasColumnType("int")
                        .HasColumnName("fStock");

                    b.HasKey("FProductId")
                        .HasName("PK_Products");

                    b.HasIndex("FBrandId");

                    b.HasIndex("FProductsCategoryId");

                    b.HasIndex(new[] { "FProductNo" }, "UQ_Products_ProductNo")
                        .IsUnique();

                    b.ToTable("tProduct", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductFavorite", b =>
                {
                    b.Property<int>("FFavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fFavoriteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FFavoriteId"));

                    b.Property<DateTime>("FCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FProductId")
                        .HasColumnType("int")
                        .HasColumnName("fProductID");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_Id");

                    b.HasKey("FFavoriteId")
                        .HasName("PK_Favorites");

                    b.HasIndex("FProductId");

                    b.HasIndex(new[] { "FUsersId", "FProductId" }, "UQ_Favorites_User_Product")
                        .IsUnique();

                    b.ToTable("t_Product_Favorite", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductImage", b =>
                {
                    b.Property<int>("FProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("fProductImageID");

                    b.Property<DateTime>("FCreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedDate");

                    b.Property<string>("FImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fImageUrl");

                    b.Property<int>("FProductId")
                        .HasColumnType("int")
                        .HasColumnName("fProductID");

                    b.Property<short>("FSortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("fSortOrder");

                    b.HasKey("FProductImageId")
                        .HasName("PK_ProductImage");

                    b.HasIndex("FProductId");

                    b.ToTable("tProductImage", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductReview", b =>
                {
                    b.Property<int>("FReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FReviewId"));

                    b.Property<string>("FComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fComment");

                    b.Property<DateTime>("FCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FOrderDetailsId")
                        .HasColumnType("int")
                        .HasColumnName("fOrderDetailsID");

                    b.Property<int>("FProductId")
                        .HasColumnType("int")
                        .HasColumnName("fProductID");

                    b.Property<byte>("FRating")
                        .HasColumnType("tinyint")
                        .HasColumnName("fRating");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_Id");

                    b.HasKey("FReviewId")
                        .HasName("PK_ProductReviews");

                    b.HasIndex("FProductId");

                    b.HasIndex(new[] { "FOrderDetailsId" }, "UQ_ProductReviews_OrderDetailsID")
                        .IsUnique();

                    b.ToTable("tProductReview", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductsCategory", b =>
                {
                    b.Property<int>("FCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("fCategoryID");

                    b.Property<string>("FCategoriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fCategoriesName");

                    b.Property<int?>("FParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("fParentCategoryId");

                    b.HasKey("FCategoryId")
                        .HasName("PK_ProductsCategory");

                    b.HasIndex("FParentCategoryId");

                    b.ToTable("tProductsCategory", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipe", b =>
                {
                    b.Property<int>("FRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FRecipeId"));

                    b.Property<int>("FAuthorUserId")
                        .HasColumnType("int")
                        .HasColumnName("fAuthorUserId");

                    b.Property<string>("FCoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fCoverImageUrl");

                    b.Property<DateTime>("FCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FDefaultServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("fDefaultServings");

                    b.Property<string>("FDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fDescription");

                    b.Property<bool>("FIsAiGenerated")
                        .HasColumnType("bit")
                        .HasColumnName("fIsAiGenerated");

                    b.Property<int>("FStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("fStatus");

                    b.Property<string>("FTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fTitle");

                    b.Property<int>("FTotalCookingMinutes")
                        .HasColumnType("int")
                        .HasColumnName("fTotalCookingMinutes");

                    b.Property<DateTime>("FUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fUpdatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FViewCount")
                        .HasColumnType("int")
                        .HasColumnName("fViewCount");

                    b.HasKey("FRecipeId")
                        .HasName("PK__tRecipe__EF3B24C700A1C89D");

                    b.ToTable("tRecipe", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeFavorite", b =>
                {
                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<DateTime>("FCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FUserId", "FRecipeId")
                        .HasName("PK_RecipeFavorites");

                    b.HasIndex("FRecipeId");

                    b.ToTable("tRecipeFavorite", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeIngredient", b =>
                {
                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<int>("FIngredientId")
                        .HasColumnType("int")
                        .HasColumnName("fIngredientId");

                    b.Property<decimal>("FRequiredQuantity")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fRequiredQuantity");

                    b.Property<string>("FUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fUnit");

                    b.HasKey("FRecipeId", "FIngredientId")
                        .HasName("PK_RecipeIngredients");

                    b.HasIndex("FIngredientId");

                    b.ToTable("tRecipeIngredient", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeLike", b =>
                {
                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<DateTime>("FCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FUserId", "FRecipeId")
                        .HasName("PK_RecipeLikes");

                    b.HasIndex("FRecipeId");

                    b.ToTable("tRecipeLike", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeRecreation", b =>
                {
                    b.Property<int>("FRecreationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fRecreationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FRecreationId"));

                    b.Property<DateTime>("FCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fNotes");

                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<string>("FRecreationImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fRecreationImageUrl");

                    b.Property<int>("FServingsCooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("fServingsCooked");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.HasKey("FRecreationId")
                        .HasName("PK__tRecipeR__5F32237EC6D73112");

                    b.HasIndex("FRecipeId");

                    b.ToTable("tRecipeRecreation", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeStep", b =>
                {
                    b.Property<int>("FStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fStepId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FStepId"));

                    b.Property<string>("FImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fImageUrl");

                    b.Property<string>("FInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fInstruction");

                    b.Property<int>("FRecipeId")
                        .HasColumnType("int")
                        .HasColumnName("fRecipeId");

                    b.Property<int>("FStepNumber")
                        .HasColumnType("int")
                        .HasColumnName("fStepNumber");

                    b.Property<int?>("FTimerSeconds")
                        .HasColumnType("int")
                        .HasColumnName("fTimerSeconds");

                    b.HasKey("FStepId")
                        .HasName("PK__tRecipeS__D4B885FFF71D234F");

                    b.HasIndex("FRecipeId");

                    b.ToTable("tRecipeStep", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecommendation", b =>
                {
                    b.Property<long>("FRecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fRecommendationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FRecommendationId"));

                    b.Property<string>("FContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fContent");

                    b.Property<DateOnly?>("FEndDate")
                        .HasColumnType("date")
                        .HasColumnName("fEndDate");

                    b.Property<bool>("FIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("fIsActive")
                        .HasDefaultValue(true, "DF_Recommendation_IsActive");

                    b.Property<int>("FPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fPriority")
                        .HasDefaultValue(1, "DF_Recommendation_Priority");

                    b.Property<long>("FRestaurantId")
                        .HasColumnType("bigint")
                        .HasColumnName("fRestaurantID");

                    b.Property<DateOnly?>("FStartDate")
                        .HasColumnType("date")
                        .HasColumnName("fStartDate");

                    b.Property<string>("FTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fTitle");

                    b.HasKey("FRecommendationId")
                        .HasName("PK__tRecomme__A41CD6C95F3659E0");

                    b.HasIndex("FRestaurantId");

                    b.ToTable("tRecommendation", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurant", b =>
                {
                    b.Property<long>("FRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fRestaurantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FRestaurantId"));

                    b.Property<string>("FAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("fAddress");

                    b.Property<string>("FBusinessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fBusinessStatus")
                        .HasDefaultValue("Operational", "DF_Restaurant_BusinessStatus");

                    b.Property<long>("FCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("fCategoryID");

                    b.Property<DateTime>("FCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fCreatedTime")
                        .HasDefaultValueSql("(getdate())", "DF_Restaurant_CreatedTime");

                    b.Property<string>("FDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fDescription");

                    b.Property<string>("FGooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fGooglePlaceID");

                    b.Property<decimal?>("FGoogleRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("fGoogleRating");

                    b.Property<int>("FGoogleReviewCount")
                        .HasColumnType("int")
                        .HasColumnName("fGoogleReviewCount");

                    b.Property<bool>("FIsRecommend")
                        .HasColumnType("bit")
                        .HasColumnName("fIsRecommend");

                    b.Property<decimal>("FLatitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("fLatitude");

                    b.Property<decimal>("FLongitude")
                        .HasColumnType("decimal(10, 7)")
                        .HasColumnName("fLongitude");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fName");

                    b.Property<string>("FPhone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fPhone");

                    b.Property<DateTime?>("FUpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("fUpdatedTime");

                    b.HasKey("FRestaurantId")
                        .HasName("PK__tRestaur__B18244B3A32FA8C5");

                    b.HasIndex("FCategoryId");

                    b.HasIndex(new[] { "FGooglePlaceId" }, "UQ_Restaurant_GooglePlaceID")
                        .IsUnique();

                    b.ToTable("tRestaurant", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurantCategory", b =>
                {
                    b.Property<long>("FCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FCategoryId"));

                    b.Property<string>("FCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fCategoryName");

                    b.Property<DateTime>("FCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fCreatedTime")
                        .HasDefaultValueSql("(getdate())", "DF_RestaurantCategory_CreatedTime");

                    b.Property<string>("FDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fDescription");

                    b.HasKey("FCategoryId")
                        .HasName("PK__tRestaur__53E607D33243056A");

                    b.ToTable("tRestaurantCategory", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurantImage", b =>
                {
                    b.Property<long>("FImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FImageId"));

                    b.Property<string>("FImageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fImageType")
                        .HasDefaultValue("Google", "DF_RestaurantImage_ImageType");

                    b.Property<string>("FImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fImageUrl");

                    b.Property<long>("FRestaurantId")
                        .HasColumnType("bigint")
                        .HasColumnName("fRestaurantID");

                    b.HasKey("FImageId")
                        .HasName("PK__tRestaur__39CAEC2A27FDBB83");

                    b.HasIndex("FRestaurantId");

                    b.ToTable("tRestaurantImage", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TSeller", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<DateTime>("FApplyDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fApplyDate");

                    b.Property<string>("FDescription")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("fDescription");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fName");

                    b.Property<int>("FStatus")
                        .HasColumnType("int")
                        .HasColumnName("fStatus");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.HasKey("FId")
                        .HasName("PK__tSeller__D9F8227CC2CEEF95");

                    b.HasIndex("FStatus");

                    b.HasIndex("FUserId");

                    b.ToTable("tSeller", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TShoppingCart", b =>
                {
                    b.Property<int>("FCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fCartItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FCartItemId"));

                    b.Property<DateTime>("FCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FProductId")
                        .HasColumnType("int")
                        .HasColumnName("fProductId");

                    b.Property<int>("FQuantity")
                        .HasColumnType("int")
                        .HasColumnName("fQuantity");

                    b.Property<int>("FSellerId")
                        .HasColumnType("int")
                        .HasColumnName("fSeller_Id");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_Id");

                    b.HasKey("FCartItemId")
                        .HasName("PK_ShoppingCarts");

                    b.HasIndex("FProductId");

                    b.ToTable("tShoppingCart", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TStatus", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fName");

                    b.HasKey("FId")
                        .HasName("PK__tStatus__D9F8227CCB85E5C0");

                    b.ToTable("tStatus", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTag", b =>
                {
                    b.Property<int>("FTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fTagId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FTagId"));

                    b.Property<string>("FCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fCategory");

                    b.Property<string>("FTagName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("fTagName");

                    b.HasKey("FTagId")
                        .HasName("PK__tTag__036309757A066FA3");

                    b.ToTable("tTag", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTrip", b =>
                {
                    b.Property<long>("FTripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fTripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FTripId"));

                    b.Property<DateTime>("FCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fCreatedTime")
                        .HasDefaultValueSql("(getdate())", "DF_Trip_CreatedTime");

                    b.Property<string>("FDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fDescription");

                    b.Property<TimeOnly?>("FStartTime")
                        .HasColumnType("time")
                        .HasColumnName("fStartTime");

                    b.Property<string>("FStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fStatus")
                        .HasDefaultValue("Draft", "DF_Trip_Status");

                    b.Property<DateOnly>("FTripDate")
                        .HasColumnType("date")
                        .HasColumnName("fTripDate");

                    b.Property<string>("FTripName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fTripName");

                    b.Property<DateTime?>("FUpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("fUpdatedTime");

                    b.Property<int>("FUsersId")
                        .HasColumnType("int")
                        .HasColumnName("fUsers_ID");

                    b.HasKey("FTripId")
                        .HasName("PK__tTrip__704F7E1DFE254E51");

                    b.HasIndex("FUsersId");

                    b.ToTable("tTrip", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTripRestaurant", b =>
                {
                    b.Property<long>("FTripRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fTripRestaurantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FTripRestaurantId"));

                    b.Property<DateTime>("FCreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fCreatedTime")
                        .HasDefaultValueSql("(getdate())", "DF_TripRestaurant_CreatedTime");

                    b.Property<string>("FNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fNote");

                    b.Property<long>("FRestaurantId")
                        .HasColumnType("bigint")
                        .HasColumnName("fRestaurantID");

                    b.Property<int>("FSortOrder")
                        .HasColumnType("int")
                        .HasColumnName("fSortOrder");

                    b.Property<int?>("FStayMinutes")
                        .HasColumnType("int")
                        .HasColumnName("fStayMinutes");

                    b.Property<long>("FTripId")
                        .HasColumnType("bigint")
                        .HasColumnName("fTripID");

                    b.Property<TimeOnly?>("FVisitTime")
                        .HasColumnType("time")
                        .HasColumnName("fVisitTime");

                    b.HasKey("FTripRestaurantId")
                        .HasName("PK__tTripRes__6D75C5210DB38984");

                    b.HasIndex("FRestaurantId");

                    b.HasIndex(new[] { "FTripId", "FSortOrder" }, "UQ_TripRestaurant_SortOrder")
                        .IsUnique();

                    b.ToTable("tTripRestaurant", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TUser", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FId"));

                    b.Property<string>("FAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fAddress");

                    b.Property<DateTime>("FCreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fCreateDate");

                    b.Property<string>("FEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("fEmail");

                    b.Property<bool>("FGender")
                        .HasColumnType("bit")
                        .HasColumnName("fGender");

                    b.Property<string>("FIdNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fId_num");

                    b.Property<bool>("FIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("fIsActive");

                    b.Property<DateTime?>("FLastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("fLastLogin");

                    b.Property<string>("FNickname")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fNickname");

                    b.Property<byte[]>("FPassword")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varbinary(40)")
                        .HasColumnName("fPassword");

                    b.Property<string>("FPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fPhone");

                    b.Property<string>("FProfileImg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("fProfileImg");

                    b.Property<string>("FUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fUsername");

                    b.HasKey("FId")
                        .HasName("PK__tUser__D9F8227CA4B2B9CC");

                    b.HasIndex(new[] { "FEmail" }, "UQ__tUser__E609A9E550B0079B")
                        .IsUnique();

                    b.ToTable("tUser", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TUserFollow", b =>
                {
                    b.Property<int>("FFollowerId")
                        .HasColumnType("int")
                        .HasColumnName("fFollowerId");

                    b.Property<int>("FFolloweeId")
                        .HasColumnType("int")
                        .HasColumnName("fFolloweeId");

                    b.Property<DateTime>("FCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fCreatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FFollowerId", "FFolloweeId")
                        .HasName("PK_UserFollows");

                    b.ToTable("tUserFollow", (string)null);
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TUserPantry", b =>
                {
                    b.Property<int>("FPantryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("fPantryItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FPantryItemId"));

                    b.Property<DateOnly>("FExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("fExpiryDate");

                    b.Property<int>("FIngredientId")
                        .HasColumnType("int")
                        .HasColumnName("fIngredientId");

                    b.Property<decimal>("FStockQuantity")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fStockQuantity");

                    b.Property<int>("FUserId")
                        .HasColumnType("int")
                        .HasColumnName("fUserId");

                    b.HasKey("FPantryItemId")
                        .HasName("PK__tUserPan__762E20883F09334E");

                    b.HasIndex("FIngredientId");

                    b.ToTable("tUserPantry", (string)null);
                });

            modelBuilder.Entity("TRecipeTag", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRecipe", null)
                        .WithMany()
                        .HasForeignKey("FRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeTags_Recipes");

                    b.HasOne("prjMvcCore第四組.Models.TTag", null)
                        .WithMany()
                        .HasForeignKey("FTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeTags_Tags");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TApply", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUser")
                        .WithMany("TApplies")
                        .HasForeignKey("FUserId")
                        .IsRequired()
                        .HasConstraintName("FK_tApply_tUser");

                    b.Navigation("FUser");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TMapFavorite", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRestaurant", "FRestaurant")
                        .WithMany("TMapFavorites")
                        .HasForeignKey("FRestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Restaurant");

                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUsers")
                        .WithMany("TMapFavorites")
                        .HasForeignKey("FUsersId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorite_Users_");

                    b.Navigation("FRestaurant");

                    b.Navigation("FUsers");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TMessageTable", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TPostTable", "FPost")
                        .WithMany("TMessageTables")
                        .HasForeignKey("FPostId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageTable_PostTable");

                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUser")
                        .WithMany("TMessageTables")
                        .HasForeignKey("FUserId")
                        .IsRequired()
                        .HasConstraintName("FK_MessageTable_User");

                    b.Navigation("FPost");

                    b.Navigation("FUser");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrderDetail", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TOrder", "FOrder")
                        .WithMany("TOrderDetails")
                        .HasForeignKey("FOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("prjMvcCore第四組.Models.TProduct", "FProduct")
                        .WithMany("TOrderDetails")
                        .HasForeignKey("FProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.Navigation("FOrder");

                    b.Navigation("FProduct");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrderDiscount", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TCoupon", "FCoupon")
                        .WithMany("TOrderDiscounts")
                        .HasForeignKey("FCouponId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDiscounts_Coupons");

                    b.HasOne("prjMvcCore第四組.Models.TOrder", "FOrder")
                        .WithMany("TOrderDiscounts")
                        .HasForeignKey("FOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDiscounts_Orders");

                    b.Navigation("FCoupon");

                    b.Navigation("FOrder");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TPostTable", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUser")
                        .WithMany("TPostTables")
                        .HasForeignKey("FUserId")
                        .IsRequired()
                        .HasConstraintName("FK_PostTable_User");

                    b.Navigation("FUser");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProduct", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TBrand", "FBrand")
                        .WithMany("TProducts")
                        .HasForeignKey("FBrandId")
                        .HasConstraintName("FK_Products_Brands");

                    b.HasOne("prjMvcCore第四組.Models.TProductsCategory", "FProductsCategory")
                        .WithMany("TProducts")
                        .HasForeignKey("FProductsCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_ProductsCategories");

                    b.Navigation("FBrand");

                    b.Navigation("FProductsCategory");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductFavorite", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TProduct", "FProduct")
                        .WithMany("TProductFavorites")
                        .HasForeignKey("FProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Products");

                    b.Navigation("FProduct");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductImage", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TProduct", "FProduct")
                        .WithMany("TProductImages")
                        .HasForeignKey("FProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductImage_Products");

                    b.Navigation("FProduct");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductReview", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TOrderDetail", "FOrderDetails")
                        .WithOne("TProductReview")
                        .HasForeignKey("prjMvcCore第四組.Models.TProductReview", "FOrderDetailsId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_OrderDetails");

                    b.HasOne("prjMvcCore第四組.Models.TProduct", "FProduct")
                        .WithMany("TProductReviews")
                        .HasForeignKey("FProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_Products");

                    b.Navigation("FOrderDetails");

                    b.Navigation("FProduct");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductsCategory", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TProductsCategory", "FParentCategory")
                        .WithMany("InverseFParentCategory")
                        .HasForeignKey("FParentCategoryId")
                        .HasConstraintName("FK_ProductsCategory_ProductsCategory");

                    b.Navigation("FParentCategory");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeFavorite", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRecipe", "FRecipe")
                        .WithMany("TRecipeFavorites")
                        .HasForeignKey("FRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeFavorites_Recipes");

                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUser")
                        .WithMany("TRecipeFavorites")
                        .HasForeignKey("FUserId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeFavorite_User");

                    b.Navigation("FRecipe");

                    b.Navigation("FUser");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeIngredient", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TIngredient", "FIngredient")
                        .WithMany("TRecipeIngredients")
                        .HasForeignKey("FIngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredients_Ingredients");

                    b.HasOne("prjMvcCore第四組.Models.TRecipe", "FRecipe")
                        .WithMany("TRecipeIngredients")
                        .HasForeignKey("FRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredients_Recipes");

                    b.Navigation("FIngredient");

                    b.Navigation("FRecipe");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeLike", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRecipe", "FRecipe")
                        .WithMany("TRecipeLikes")
                        .HasForeignKey("FRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeLikes_Recipes");

                    b.Navigation("FRecipe");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeRecreation", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRecipe", "FRecipe")
                        .WithMany("TRecipeRecreations")
                        .HasForeignKey("FRecipeId")
                        .IsRequired()
                        .HasConstraintName("FK_RecipeRecreations_Recipes");

                    b.Navigation("FRecipe");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipeStep", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRecipe", "FRecipe")
                        .WithMany("TRecipeSteps")
                        .HasForeignKey("FRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeSteps_Recipes");

                    b.Navigation("FRecipe");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecommendation", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRestaurant", "FRestaurant")
                        .WithMany("TRecommendations")
                        .HasForeignKey("FRestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK_Recommendation_Restaurant");

                    b.Navigation("FRestaurant");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurant", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRestaurantCategory", "FCategory")
                        .WithMany("TRestaurants")
                        .HasForeignKey("FCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Restaurant_Category");

                    b.Navigation("FCategory");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurantImage", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRestaurant", "FRestaurant")
                        .WithMany("TRestaurantImages")
                        .HasForeignKey("FRestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK_RestaurantImage_Restaurant");

                    b.Navigation("FRestaurant");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TSeller", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TStatus", "FStatusNavigation")
                        .WithMany("TSellers")
                        .HasForeignKey("FStatus")
                        .IsRequired()
                        .HasConstraintName("FK_tSeller_tStatus");

                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUser")
                        .WithMany("TSellers")
                        .HasForeignKey("FUserId")
                        .IsRequired()
                        .HasConstraintName("FK_tSeller_tUser");

                    b.Navigation("FStatusNavigation");

                    b.Navigation("FUser");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TShoppingCart", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TProduct", "FProduct")
                        .WithMany("TShoppingCarts")
                        .HasForeignKey("FProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingCarts_Products");

                    b.Navigation("FProduct");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTrip", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TUser", "FUsers")
                        .WithMany("TTrips")
                        .HasForeignKey("FUsersId")
                        .IsRequired()
                        .HasConstraintName("FK_Trip_Users_");

                    b.Navigation("FUsers");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTripRestaurant", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TRestaurant", "FRestaurant")
                        .WithMany("TTripRestaurants")
                        .HasForeignKey("FRestaurantId")
                        .IsRequired()
                        .HasConstraintName("FK_TripRestaurant_Restaurant");

                    b.HasOne("prjMvcCore第四組.Models.TTrip", "FTrip")
                        .WithMany("TTripRestaurants")
                        .HasForeignKey("FTripId")
                        .IsRequired()
                        .HasConstraintName("FK_TripRestaurant_Trip");

                    b.Navigation("FRestaurant");

                    b.Navigation("FTrip");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TUserPantry", b =>
                {
                    b.HasOne("prjMvcCore第四組.Models.TIngredient", "FIngredient")
                        .WithMany("TUserPantries")
                        .HasForeignKey("FIngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPantry_Ingredients");

                    b.Navigation("FIngredient");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TBrand", b =>
                {
                    b.Navigation("TProducts");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TCoupon", b =>
                {
                    b.Navigation("TOrderDiscounts");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TIngredient", b =>
                {
                    b.Navigation("TRecipeIngredients");

                    b.Navigation("TUserPantries");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrder", b =>
                {
                    b.Navigation("TOrderDetails");

                    b.Navigation("TOrderDiscounts");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TOrderDetail", b =>
                {
                    b.Navigation("TProductReview");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TPostTable", b =>
                {
                    b.Navigation("TMessageTables");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProduct", b =>
                {
                    b.Navigation("TOrderDetails");

                    b.Navigation("TProductFavorites");

                    b.Navigation("TProductImages");

                    b.Navigation("TProductReviews");

                    b.Navigation("TShoppingCarts");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TProductsCategory", b =>
                {
                    b.Navigation("InverseFParentCategory");

                    b.Navigation("TProducts");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRecipe", b =>
                {
                    b.Navigation("TRecipeFavorites");

                    b.Navigation("TRecipeIngredients");

                    b.Navigation("TRecipeLikes");

                    b.Navigation("TRecipeRecreations");

                    b.Navigation("TRecipeSteps");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurant", b =>
                {
                    b.Navigation("TMapFavorites");

                    b.Navigation("TRecommendations");

                    b.Navigation("TRestaurantImages");

                    b.Navigation("TTripRestaurants");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TRestaurantCategory", b =>
                {
                    b.Navigation("TRestaurants");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TStatus", b =>
                {
                    b.Navigation("TSellers");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TTrip", b =>
                {
                    b.Navigation("TTripRestaurants");
                });

            modelBuilder.Entity("prjMvcCore第四組.Models.TUser", b =>
                {
                    b.Navigation("TApplies");

                    b.Navigation("TMapFavorites");

                    b.Navigation("TMessageTables");

                    b.Navigation("TPostTables");

                    b.Navigation("TRecipeFavorites");

                    b.Navigation("TSellers");

                    b.Navigation("TTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
